[build]
  publish = "public"
  functions = "functions"
  command = "npm run build"
  
[build.environment]
  NODE_VERSION = "12"

  [[redirects]]
  from = "/api/*"
  to = "/portfolio"
  status = 200

[[plugins]]
  package = "netlify-plugin-gatsby-cache"


